// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Error = { type: "BadRequest"; error: string } | { type: "Internal"; error: string }

export type ProceduresLegacy = { queries: never; mutations: { key: "scan"; input: { path: string }; result: null }; subscriptions: never }

export type Procedures = {
	scan: { kind: "mutation", input: { path: string }, output: null, error: Error },
}